- name: Install python3
  apt: pkg=python3
  become: yes

- name: Install pip3
  apt: pkg=python3-pip
  become: yes

- name: Upgrade pip
  pip: name=pip extra_args=--upgrade executable=pip3
  become: yes

- name: Install python setuptools
  apt: pkg=python3-setuptools
  become: yes
